gemspec: linkbot.gemspec
bump_version: true
targets: [cent6]
build:
  dependencies:
    cent6:
      - rubygems19
      - ruby19-devel
      - sqlite-devel
      - openssl-devel
  commands: |
    sudo gem install bundler
    bundle install --system --without test
    bundle package
contents:
  - bin/
  - lib/
  - vendor/
install:
  prefix: /mnt/services/linkbot
  commands: |
    gem install /mnt/services/linkbot/vendor/cache/* --no-rdoc --no-ri

    cat > /usr/local/bin/linkbot <<-EOF
    	#!/bin/bash

    	exec /usr/bin/env ruby -C/mnt/services/linkbot bin/linkbot "\$@"
    EOF
    chmod 755 /usr/local/bin/linkbot

    runit_service_recreate linkbot root "/usr/local/bin/linkbot --bind /var/run/linkbot.sock --log-level debug" || true
    runit_wait_for linkbot || true

    rm -f /var/log/twilio/linkbot.log
    ln -s /service/linkbot/log/main/current /var/log/twilio/linkbot.log
